
export enum  ORDATA_TYPES {
    FETCH_DATA_START  = 'ordata/FETCH_CALENDAR_DATA_START',
    FETCH_DATA_FAILED  ='ordata/FETCH_CALENDAR_DATA_FAILED',
    FETCH_CALENDAR_DATA_SUCCESS  ='ordata/FETCH_CALENDAR_DATA_SUCCESS',
    FETCH_GRID_DATA_SUCCESS  ='ordata/FETCH_GRID_DATA_SUCCESS',
} 